name: Lint and Format Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  typescript-lint:
    name: TypeScript Lint & Format
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Check Prettier formatting
      run: npm run format:check
      
    - name: Run Prettier (fix)
      run: npm run format
      
    - name: Check for changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Prettier made changes to files"
          git diff
          exit 1
        fi

  python-lint:
    name: Python Lint & Format
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Run Black (check)
      run: black --check --diff src/ tests/
      
    - name: Run Black (format)
      run: black src/ tests/
      
    - name: Run isort (check)
      run: isort --check-only --diff src/ tests/
      
    - name: Run isort (format)
      run: isort src/ tests/
      
    - name: Run flake8
      run: flake8 --max-line-length=120 --extend-ignore=E203,W503,E501 src/ tests/
      
    - name: Check for changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Black/isort made changes to files"
          git diff
          exit 1
        fi

  combined-check:
    name: Combined Check
    runs-on: ubuntu-latest
    needs: [typescript-lint, python-lint]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Node.js dependencies
      run: npm install
      
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Run all checks
      run: |
        echo "Running TypeScript checks..."
        npm run lint
        npm run format:check
        
        echo "Running Python checks..."
        black --check src/ tests/
        isort --check-only src/ tests/
        flake8 --max-line-length=120 --extend-ignore=E203,W503,E501 src/ tests/
        
    - name: Success message
      run: |
        echo "✅ All linting and formatting checks passed!"
        echo "📝 TypeScript: ESLint + Prettier"
        echo "🐍 Python: Black + isort + flake8" 